### ISSUE TITLE
Plugin seems to recognize ">=" version comparator as "=="

### ISSUE THREAD

**Issue by osjerick** [meanmail-dev/requirements#10]
The plugin raises a warning for ">=" dependencies if you have installed updated versions of the package. Warning says the package version is not installed and is required, but this version comparator is not strict. PyCharm default accepts these cases as correct.

**Comment by meanmail** [comment]
So far, only '==' is supported. In version 2019.7, support for other comparators will be implemented

**Comment by stygmate** [comment]
+1 for this feature :)

**Comment by EpicWink** [comment]
Same for `~=`

**Comment by svaningelgem** [comment]
+1 for supporting all operators as described by the PEPs mentioned in the readme.

**Comment by meanmail** [comment]
Fixed in 2020.5. New version available for download
