### ISSUE TITLE
Red marks on outdated package with "=="

### ISSUE THREAD

**Issue by DemianS** [meanmail-dev/requirements#23]
**Describe the bug**
PyCharm marks with red any packages that outdated but I have "==" equality

**To Reproduce**
Just set some outdated version

**Expected behavior**
I thought "==" means only particular version of that package, and if I need next version I have to set ">="

**Screenshots**
![Screenshot_Req_1](https://user-images.githubusercontent.com/8601186/74222212-071f9500-4cc5-11ea-8b4f-606402b371d0.png)

**IDE:**
PyCharm 2019.3.2 (Community Edition)
Build #PC-193.6015.41, built on January 21, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: IdeaVIM, Key Promoter X, com.jetbrains.plugins.ini4idea, mobi.hsz.idea.gitignore, ru.meanmail.plugin.requirements

**Plugin:**
 - Version 2020.1-193

**Additional context**
So, maybe add another one type of checks that leads to that type of message? With green mark about suggestion to update package.

And thank you for your work.

**Comment by meanmail** [comment]
It seems that this is no longer relevant. Reopen if I'm wrong
