### ISSUE TITLE
PyCharm reports "Inspection #InstalledPackageInspection has no description"

### ISSUE THREAD

**Issue by allanlewis** [meanmail-dev/requirements#24]
**Describe the bug**
PyCharm reports an error:

> Inspection #InstalledPackageInspection has no description

**To Reproduce**
1. Install the plugin.
2. Restart PyCharm.
I'm not sure precisely when this started happening, but I don't think there's any particular config that triggers it.

**Expected behavior**
No IDE errors.

**Screenshots**
![stacktrace](https://user-images.githubusercontent.com/194736/74250918-3fce6700-4ce3-11ea-8929-85ff520d08ba.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
```
PyCharm 2019.3.3 (Community Edition)
Build #PC-193.6494.30, built on February 6, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.15-300.fc31.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1921M
Cores: 8
Registry: 
```

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version: 2020.1-193

**Additional context**
See [stacktrace](https://github.com/meanmail/requirements/files/4186458/stacktrace.txt), copied from the error dialog in PyCharm.

**Comment by meanmail** [comment]
Fixed in 2020.5
