### ISSUE TITLE
pypi url gives 404

### ISSUE THREAD

**Issue by apie** [meanmail-dev/requirements#27]
**Describe the bug**
Pypi has changed the urls for package summary. Ctrl+click on a package name from the editor opens the wrong url now.

**To Reproduce**
1. Go to 'requirements.txt' in your editor.
2. Ctrl+click on a package name. Eg: `django-push-notifications`
3. https://pypi.org/pypi/django-push-notifications opens
4. It is an error page

**Expected behavior**
https://pypi.org/project/django-push-notifications/ opens (note the trailing slash)

**Screenshots**

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Linux mint
 - Product: PyCharm professional
 - Version 2019.3
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Project SDK: Python 3.7

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2020.1-193

**Additional context**

**Comment by apie** [comment]
Ah, it seems Pypi now forwards the old url to the new URL :smile: 
Still it would be good to update the plugin to the new URL.

**Comment by 1oglop1** [comment]
I think think this is not related to the plugin, according to this it comes directly from JB library
https://github.com/meanmail-dev/requirements/blob/d3df730f36c367e7f5d0378f2ea047dc61370684/src/main/kotlin/ru/meanmail/psi/impl/VersionOneImpl.kt#L10
