### ISSUE TITLE
Invalid parsing of python_version

### ISSUE THREAD

**Issue by fmigneault** [meanmail-dev/requirements#30]
**Describe the bug**

Python version support added #20 is not working all the time.

1. Incorrect parsing of `git+http` link combined with `python_version` requirement.

2. Parsing works in other situations, but the highlighting is inconsistent.
eg: 
`flufl.enum` and `gunicorn` shown as active although they aren't because of Python version but 
`cwltool>=1....` correctly disabled with same Python condition.

Similar `python_version` specifiers seem to work on Windows machine (same plugin/PyCharm version).

**Screenshots**

**On Ubuntu - Python 3**
![image](https://user-images.githubusercontent.com/19194484/80766825-4ca96c80-8b14-11ea-8a84-57e6fec6c4a7.png)

**On Windows - Python 3**
![image](https://user-images.githubusercontent.com/19194484/80766951-9f832400-8b14-11ea-8ce7-11b93ae007ed.png)

**IDE:**
PyCharm 2020.1 (Community Edition)
Build #PC-201.6668.115, built on April 7, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-99-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.windowSystem.autoShowProcessPopup=true, projectView.hide.dot.idea=false, documentation.show.toolbar=true, debugger.mayBringFrameToFrontOnBreakpoint=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, zielu.gittoolbox, GrepConsole, Pip requirements info bubble, SnakeYAML plugin, cc.duduhuo.git-conflict, codes.rudolph.idea.cfg, com.alayouni.ansiHighlight, com.andrey4623.rainbowcsv, com.intellij.ideolog, com.ivanovych666.intellij.plugin.jsonsorter, com.jetbrains.plugins.ini4idea, mobi.hsz.idea.gitignore, ideanginx9, jp.co.future.ideausqlfmt, jp.roundrop.sqlformatter, krasa.CpuUsageIndicator, lermitage.intellij.extra.icons, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, BashSupport, com.cegin.PUTVT, net.ashald.envfile, python-flake8, ru.meanmail.plugin.requirements, AWSCloudFormation, Docker, ru.adelf.idea.dotenv, org.zalando.intellij.swagger, org.sylfra.idea.plugins.linessorter, hunspell
Current Desktop: Unity

**Plugin**
 - Version 2020.201

**Comment by meanmail** [comment]
Fixed in 2020.4. Available for download
