### ISSUE TITLE
Install-ALL and Update-ALL buttons

### ISSUE THREAD

**Issue by Luk164** [meanmail-dev/requirements#34]
**Is your feature request related to a problem? Please describe.**
I have to manually go through all packages and install hem

**Describe the solution you'd like**
An install-ALL and maybe update-ALL button. Accessible via pop-up banner and context menu of requirements.txt file.

**Comment by meanmail** [comment]
Good idea

**Comment by meanmail** [comment]
In version 2020.2:
Added action `Install All Packages` to the context menu. Not Recursively installs all packages specified in the file
