### ISSUE TITLE
New package version false positive

### ISSUE THREAD

**Issue by bryant1410** [meanmail-dev/requirements#37]
**Describe the bug**
It warns that there's a newer version of certain package but it's actually order. I have 0.27.0 but it says there's the 0.3 which claims it's newer.

**To Reproduce**
1. Add a package in `requirements.txt` in which the latest version has 2 digits over an older one.
4. See error in the warning.

**Expected behavior**
It shouldn't warn anything.

**Screenshots**

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Ubuntu 20.04
 - Product: PyCharm Professional
 - Version 2020.1
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Project SDK: Python 3.8.3

**Plugin:**
 - Version 2020.1-201

**Additional context**
I think it's comparing the versions as strings, as opposed to numbers.

**Comment by meanmail** [comment]
> I think it's comparing the versions as strings, as opposed to numbers.

Versions are not compared as strings. It uses intellij code specifically designed to compare python package versions

I can not reproduce this error. Please give me the package name

**Comment by bryant1410** [comment]
Sorry, but I can't share the package name because it's from a private package index. I can say the following. In requirements.txt, the package name is specified by itself without a version, just the name. The version that I have installed it's `0.27.0` and it says that "version `0.3` is not installed (required: 0.3, installed: 0.27.0, latest: 0.3)".

**Comment by meanmail** [comment]
Plugin version 2021.4 supports additional repositories.

https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html#install-package

In the Manage Repositories dialog that opens, click Add a repository to add a URL of a private repository, for example, http://localhost:3141/root/pypi/+simple/, then click OK.
