### ISSUE TITLE
Option to configure multiple requirments

### ISSUE THREAD

**Issue by ItayZiv** [meanmail-dev/requirements#38]
I think it would be useful if there was an option to have multiple requirement files, for example, a normal `requirments.txt` and a `dev-requirments.txt` (useful for packages for example).

**Comment by meanmail** [comment]
The plugin supports all files with the extension `.txt`

**Comment by ItayZiv** [comment]
Yea, but it only supports a single file, while sometimes requirements may be split over multiple files

**Comment by briancappello** [comment]
@meanmail I recall this working out-of-the-box with multiple requirements files in earlier versions of PyCharm, but at least in 2020.2, this plugin now only detects `requirements.txt` for me too.

**Comment by meanmail** [comment]
Improved in 2020.4.1. Available for update

Also you can explicitly specify your file as requirements.txt file:
Settings -> Editor -> File Types -> Recognized File Types -> Requirements Language -> File name pattern
