### ISSUE TITLE
Local file path requirement breaks parsing

### ISSUE THREAD

**Issue by tomas-sk** [meanmail-dev/requirements#39]
**Describe the bug**
All rows after a local file path with subfolder are not recognized and no version checking is performed on them.

**To Reproduce**
1. Use following requirements.txt
```
icalendar==4.0.6
idna==2.8
# recognized packages above

# local file path requirement with subfolders ("/" causes the bug)
install/pkg/gdata-3.0.1-py3-none-any.whl

# all following packages are unrecognized
iso8601==0.1.12
jinja2==2.10.1
kombu==4.6.11
lxml>=4.2.5,<=4.3.0
```

**Expected behavior**
I expect the plugin to recognize packages after local file path requirement containing "/".

**Screenshots**
![image](https://user-images.githubusercontent.com/23239606/86882985-6c02de00-c0f1-11ea-8fd3-d9cb0977ecb1.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Windows 10
 - Product: PyCharm 2020.1.2 (Professional Edition)
 - Version Build #PY-201.7846.77, built on June 1, 2020
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 - Project SDK: Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]'

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version: 2020.1-201

**Additional context**
-

**Comment by meanmail** [comment]
Fixed in 2020.4. Available for download
