### ISSUE TITLE
Updates are checked against pypi.org, even if pip conf suggest otherwise

### ISSUE THREAD

**Issue by Colin-b** [meanmail-dev/requirements#48]
I am using a private pypi repository and my pip configuration points to this repository,

Would it be possible to rely on pip to check available packages instead of only checking pypi,org?

I assume it is the issue as I can only see the new version for public packages and not my private packages.

Thanks again

**Comment by meanmail** [comment]
Private pypi repository is not supported yet

**Comment by TheFriendlyCoder** [comment]
PyCharm allows the pypi repositories to be customized on a per project basis (ie: Preferences -> Project -> Interpreter -> "+" to add new dependency -> Manage Repositories). This plugin should respect whatever values are set here in the IDE.

**Comment by meanmail** [comment]
Plugin 2021.4 supported additional repositories (Preferences -> Project -> Interpreter -> "+" to add new dependency -> Manage Repositories)
