### ISSUE TITLE
Requirements ~= is not recognized properly

### ISSUE THREAD

**Issue by profhase** [meanmail-dev/requirements#50]
https://youtrack.jetbrains.com/issue/PY-20522
**Describe the bug**

Pycharm doesn't understand "compatible release" (~=) in requirements.txt 

Having for example the following statement in `requirements.txt`

```
jsonschema~=3.2
```

I see on the very buttom the message:
> Jsonschema version 3.2 not installed, required: 3.2, installed 3.2.0, latest: 3.2.0

**To Reproduce**
1. Create new Python project in Pycharm with a new virtualenv (i did with python 3)
2. Create a requirements.txt in this project
3. Type in the line aiohttp~=3.6
4. go to this line, type Alt+Enter -> Install aiohttp in version 3.6.2 
    Here Pycharm changes the version in requirements.txt to 3.6.2
5. Change back the line into aiohttp~=3.6
6.  Here you will see the warning `aiohttp version 3.6. not installed (required 3.6, installed 3.6.2 aiohttp version is outdated ...)

**Expected behavior**
Pycharm should recognize compatible versions as such

**Screenshots**
see here:
https://youtrack.jetbrains.com/issue/PY-44453

**IDE (please complete the following information. See Main Menu -> Help -> About):**
```
PyCharm 2020.2.3 (Professional Edition)
Build #PY-202.7660.27, built on October 6, 2020
You have a perpetual fallback license for this version
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-52-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1925M
Cores: 8
Non-Bundled Plugins: org.jetbrains.plugins.vue, ru.meanmail.plugin.requirements
Current Desktop: ubuntu:GNOME
```

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version [e.g. 2020.4-202]

**Comment by meanmail** [comment]
Fixed in 2020.5. New version available for download
