### ISSUE TITLE
`sys_platform` environment marker seems unsupported

### ISSUE THREAD

**Issue by xmo-odoo** [meanmail-dev/requirements#51]
* Any requirement which uses the `sys_platform` marker is marked as "unused", even if the platform matches the system it's running on.
* Any dependency whose requirement always uses `sys_platform` is considered not listed in project requirements.

# To Reproduce

1. add a requirement using sys_platform marker e.g.

        attrs ; sys_platform == 'win32'
        attrs ; sys_platform != 'win32'

2. observe that both lines are greyed out and considered unused
3. `import attr` in project code
4. import triggers a warning "Package containing module 'attr' is not listed in project requirements."

# Expected behavior

* The requirement matching the current system should be seen as used (this is how `python_version` behaves).
* The import should be fine.

# Environment

 - OS: Mint 19
 - Product: PyCharm Community Edition
 - Version 2020.2.3
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 - Project SDK: Python 3.6
 - Plugin Version 2020.4-202

**Comment by meanmail** [comment]
Thanks! This bug will be fix in 2020.5

**Comment by meanmail** [comment]
Fixed in 2020.4.1. Available for update
