### ISSUE TITLE
Add checking "requirements" files with different names.

### ISSUE THREAD

**Issue by AIGeneratedUsername** [meanmail-dev/requirements#52]
**Is your feature request related to a problem? Please describe.**

I have the following files:
/requirements.txt
/requirements_dev.txt
/requirements_local.txt

The plugin only check automatically the "requirements.txt" file.

But I want to check all my "requirements_*.txt" files.

**Describe the solution you'd like**
Recognize "requirements" files automatically.

OR 

Allow to specify all my "requirements_*.txt" files in the plugin settings.

**Describe alternatives you've considered**
I did not find information about checking files that have name different from "requirements.txt".

**Comment by AIGeneratedUsername** [comment]
I think that I found a solution.

1. Open in PyCharm:
 **Settings -> Editor -> File Types -> Recognized File Types -> Requirements Language -> File name pattern**
2. Use regex to set `requirements*.txt` (or `requirements_*.txt`) or whatever will match your "requirements" files' names.

**Comment by meanmail** [comment]
Improved in 2020.4.1. Available for update
