### ISSUE TITLE
Installed package not found

### ISSUE THREAD

**Issue by leonardogian** [meanmail-dev/requirements#54]
**Describe the bug**
Package installed in Python 3.8 virtual environment not detected in requirements.txt. Maybe due to uppercase name? (The package is PyBoolNet==2.2.9)

**To Reproduce**
1. Install PyBoolNet==2.2.9
2. Create requirements.txt having contents PyBoolNet==2.2.9
3. See error

**Screenshots**
![Screenshot from 2020-12-16 10-29-50](https://user-images.githubusercontent.com/69602303/102330921-71126600-3f8a-11eb-9670-94ed1f4936cc.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Linux Mint 20 64 bit (5.4.0-56-generic)
 - Product: PyCharm Community
 - Version: PC-203.5981.165, 2020.3
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Project SDK: Python 3.8.5

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2020.5-203

**Comment by meanmail** [comment]
@leonardogian Packages are checked at pypi.org. The PyBoolNet package is not there. Tell me, from which source is the package installed?

**Comment by leonardogian** [comment]
@meanmail Hi, thanks for your prompt reply. You are right: that package is not registered with pypi. I am sorry for the unnecessary request.
