### ISSUE TITLE
Entry followed by -- throws error

### ISSUE THREAD

**Issue by chocoelho** [meanmail-dev/requirements#55]
**Describe the bug**
If I have an entry like `psycopg2==2.7.7 --no-binary psycopg2` in my requirements is enough to throw `RequirementsTokenType.HASH expected, got 'n'`. Anything after that is not interpreted properly. If I remove `--no-binary psycopg2`, it works fine.

**To Reproduce**
1. Just put something like `psycopg2==2.7.7 --no-binary psycopg2` in the middle of a requirements.txt file
2. Anything after that can't be properly read

**Expected behavior**
`--no-binary psycopg2` or equivalent should be understood as part of the entry in the same line or ignored without the need to comment it out.

**Screenshots**
![image](https://user-images.githubusercontent.com/3460435/103093586-87976d80-45d9-11eb-998e-df0377c0c8fa.png)
![image](https://user-images.githubusercontent.com/3460435/103093605-9847e380-45d9-11eb-955f-4ecbb523e2cc.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Windows 10
 - Product: Pycharm Professional
 - Version PY-203.6682.86, 2020.12.24
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Project SDK: Python 3.6.4

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2020.5-203

**Comment by meanmail** [comment]
Thanks for the feedback! Will be fixed in the next major release

**Comment by meanmail** [comment]
@chocoelho 
https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

Requirements File Format

...

The following options are supported:

-i, --index-url
--extra-index-url
--no-index
-c, --constraint
-r, --requirement
-e, --editable
-f, --find-links
--no-binary
--only-binary
--prefer-binary
--require-hashes
--pre
--trusted-host
--use-feature

Please note that the above options are global options, and should be specified on their individual lines. The options which can be applied to individual requirements are --install-option, --global-option and --hash.
...

**Comment by chocoelho** [comment]
Thanks for pointing that out. As things installed just fine, I found it odd that the analyzer was breaking in that line. As having the option on top of the file, in its own line, works just fine, I'm closing this issue. Not sure it's worth to add support to something that's out of the recommended file format definition.
