### ISSUE TITLE
Suggested upgrades fail when newest version of package requires newer Python version

### ISSUE THREAD

**Issue by wkeithvan** [meanmail-dev/requirements#56]
**Describe the bug**
Suggested updates don't check the installed Python version. For instance, I am working on a Python 3.6.8 project and the latest Pandas version 1.2.0 requires Python 3.7.1+. Clicking the "Install 'pandas' version 1.2.0" button generates the following error:
```
The following command was executed:
pip install pandas==1.2.0
The exit code: 1
The error output of the command:
ERROR: Could not find a version that satisfies the requirement pandas==1.2.0
ERROR: No matching distribution found for pandas==1.2.0
Non-zero exit code (1)
```

**To Reproduce**
1. Create project using older version of Python, like 3.6.8
2. Add requirement to requirements.txt that requires a newer version of Python, like Pandas 1.2.0
3. Click the "Install 'pandas' version 1.2.0" link
4. Error message (see above) appears

**Expected behavior**
The context menu should either only suggest the newest compatible version (e.g. Pandas 1.1.5 on Python 3.6) and/or inform the user that Python 3.7.1+ is necessary for Pandas 1.2.0

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Windows 10
 - Product: PyCharm Professional
 - Version: 2020.3.2
 - Project SDK: Python 3.6.8

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2020.6-203

**Comment by meanmail** [comment]
Fixed in 2020.1
