### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by xyxz-web** [meanmail-dev/requirements#58]
I'd like to use this plugin as it looks very useful, but in order to get it approved I need information on how it handles privacy.
Does it collect any personal information?
If so, what kind of data is collected and when is it collected?
Would also be great if you could add this to the documentation.

Thank you very much!

**Comment by meanmail** [comment]
Thanks for your interest in the plugin!

The production version of the plugin is built from the source codes provided in this repository. No personal information is collected when the plugin is running. When errors occur, the user can **explicitly** at will, using standard IDE methods, send error data to our error build system. We use https://sentry.io/. In this case, the information is sent in an impersonal form. It cannot be linked in any way with the identity of the user who submitted the error.
Nevertheless, we still warn you that when sending error messages, some data may get into the error message generated by the IDE. And before sending an error message, you need to make sure that no sensitive information is included in the error log. You can completely refuse to send error messages, this is an optional function and is made only for the convenience of users. We value the privacy of our users. The error messages received by us in the error collection system are never published by us and are used solely to fix errors in the plugin.
The code related to sending errors is located in https://github.com/meanmail-dev/requirements/blob/master/src/main/kotlin/ru/meanmail/diagnostic/SentryErrorReporter.kt

Thanks for the suggestion to add information to the documentation. We will do it shortly.

I hope using the plugin will make your work more enjoyable!
