### ISSUE TITLE
After updating the plugin suggests to install old packages

### ISSUE THREAD

**Issue by KonstantinLitvin** [meanmail-dev/requirements#62]
**Screenshots**
![image](https://user-images.githubusercontent.com/9830255/116919967-be9e1f80-ac5a-11eb-9728-605c3a6e04b1.png)

-PyCharm Community 2021.1.1 and PyCharm Pro 2021.1.1 on Ubuntu  20.04

**Comment by meanmail** [comment]
@KonstantinLitvin fixed. You can download the new version
