### ISSUE TITLE
Not Compatiable with PyCharm 2021.3 EAP

### ISSUE THREAD

**Issue by Baneeishaque** [meanmail-dev/requirements#68]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: [e.g. Windows 10]
 - Product: [e.g. Idea Ultimate, PyCharm Community]
 - Version [e.g. IU-192.7142.36, 2019.2.4]
 - JRE Version: [e.g. OpenJDK 64-Bit Server VM by JetBrains s.r.o]
 - Project SDK: [Python 3.7.1, Python 2.7.17]

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version [e.g. 2020.1-193]

**Additional context**

**Comment by meanmail** [comment]
New version available [Requirements 2021.4.1-213-EAP-SNAPSHOT](https://plugins.jetbrains.com/plugin/10837-requirements)
