### ISSUE TITLE
Alternative 'package is not installed' settting

### ISSUE THREAD

**Issue by fmigneault** [meanmail-dev/requirements#70]
**Is your feature request related to a problem? Please describe.**

Looking at settings, the `Requirements > Package is not installed` description indicates: 
> Checks if the required version of the package is installed.
>
> Compares the required version of the package with the installed one. If the required version is not installed, it offers to install it. If a new version is available, it offers to update the package version and install the package.

Although it is nice that the plugin can detect new versions and offer to update the package when the installed one is not the latest, I would like to have a method to represent this specific case with a different `Severity` than `Warning`. I think current flagging strategy doesn't respect the first part `Checks if the required version of the package is installed.`

More specifically, if for example I indicate `package>=1.2.3` in my requirements, I would consider an installed `package>=1.2.4` to respect the requirement specification, although `package>=1.3` could be available. I believe this should be flagged (e.g.: with `Weak Warning`) to propose the update, while not being against the requirement version. This would make a distinction with installed `package>=1.1` which doesn't fulfill the requirement, although installed. There should be two different settings for each case.

The reason I would love to have this feature is because I often apply requirements with ranges such as `package>=1.2.4,<1.5` because I couldn't care less which is the installed version vs available ones, as long as they don't directly break some specific feature in my code. Every time I look at requirements files, I have the impression something is wrong (due to `Warning`), while installed packages are valid based on my specified versions.

Furthermore, I noticed that even when specifying explicit versions (e.g.: `package==1.2.3`), the plugin will warn me that "`package==1.3` is outdated" and offer to update it. The only situation where I apply `==` is because this is a *hard* requirement, where any other version breaks the code. In this case, warnings are much more inconvenient because I specifically do not want new versions.  

**Describe the solution you'd like**
Some different setting entry to distinguish between *unfulfilled* requirements vs *proposed update* requirement based on version released. I could then leave *unfulfilled* requirements as `Warning` severity while *proposed update* would be `Weak Warning`, making it obvious at first glance if I should worry about invalid requirements or convenience update detection.

**Describe alternatives you've considered**
Looked as other settings, but everything else is about duplicated, missing or unused packages, which also are important cases but not matching my problem.

**Additional context**
Examples of cases: 
![image](https://user-images.githubusercontent.com/19194484/135556806-4425d276-9b4d-4c72-8422-6479c71dcd53.png)

![image](https://user-images.githubusercontent.com/19194484/135556802-34cff531-b629-4f88-80ba-676ee514ea93.png)

**Comment by meanmail** [comment]
Fixed in 2022.3
