### ISSUE TITLE
No matching version null

### ISSUE THREAD

**Issue by Bechma** [meanmail-dev/requirements#71]
**Describe the bug**
Some packages related to opentelemetry are not recognized by the plugin, although they are installed in the environment. It looks like it detects this packages with an ending null string

**To Reproduce**
Just type some packages from opentelemetry contrib page like:
- opentelemetry-instrumentation-fastapi
- opentelemetry-instrumentation-sqlalchemy
- opentelemetry-instrumentation-aiohttp-client
- opentelemetry-instrumentation-httpx

It will say something like:
No matching package version found: 'opentelemetry-instrumentation-XXXXnull' (required: <unknown>, installed: 0.24b0, latest: <nothing>) 

**Expected behavior**
No warnings or errors

**Screenshots**
![image](https://user-images.githubusercontent.com/19294519/137362069-1b98e2d1-49a5-4c56-a93e-664d95de374b.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Windows 10
 - Product: PyCharm Community
 - Version 2021.2.2
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Project SDK: Python 3.9.5

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2021.4.1-212

**Additional context**
I tried to remove the file and add a new one, but the same problem happens

**Comment by meanmail** [comment]
@Bechma Fixed in 2022.2
