### ISSUE TITLE
Error if multiple boolean operators of the same kind keep flat

### ISSUE THREAD

**Issue by Rongronggg9** [meanmail-dev/requirements#73]
**Describe the bug**
Error if multiple boolean operators of the same kind keep flat:
![](https://user-images.githubusercontent.com/15956627/146732405-6833715c-91e3-4e8b-abdc-bd20e365c2fd.png)

Works fine if they are nested:
![](https://user-images.githubusercontent.com/15956627/146732540-8ae03edc-48de-4a4a-9b70-92fed9f2d966.png)

Works fine if there are no more than 1 boolean operator of the same kind that appears continuously:
![](https://user-images.githubusercontent.com/15956627/146733098-35259d25-4e9e-4fb1-8b3b-db25c84ac651.png)

**To Reproduce**
```
myDep; some_condition and some_condition and ...
myDep; some_condition or some_condition or ...
```

**Expected behavior**
It should work fine in such a situation because pip works fine too :)

**Screenshots**
See above.

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Windows 11 x86_64
 - Product: PyCharm Professional
 - Version PY-213.5744.248
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 - Project SDK: Python 3.9.2

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2021.4.1-213-EAP-SNAPSHOT

**Comment by meanmail** [comment]
Fixed in 2022.3
