### ISSUE TITLE
Plugin not using appropriate conda env with multi-project

### ISSUE THREAD

**Issue by fmigneault** [meanmail-dev/requirements#76]
**Describe the bug**

When multiple projects are opened within the same app window (using attach option), the plugin starts to randomly misbehave. 
Simply put, it does not correctly detect the applied conda environment for individual projects.
Package detection and installation occurs on seemly random environments at that point.

**To Reproduce**
1. Create a few distinct projects each with their own conda env and distinct requirements.txt contents.
1. Install the requirements.txt within the respective conda env for each case (using command line).
1. Open all the projects in the same window (open one by one using attach option).
1. Move inside the requirements.txt of one project, and see many requirements not detected as installed.
1. (optional) Right click on a "missing" package to resolve/install it. Notice it might not be installed in the correct environment.

**Expected behavior**

Regardless of single project or multi-project view, the displayed requirements.txt should consider the scope of its project to detect the appropriate conda env. 

**Screenshots**

Following display my multi-project (16) view. Each directory is itself an individual PyCharm project with distinct conda envs and each with their own requirements.txt inside. In the project `File->Settings->Project->Python Interpreter` menu, each of them is properly associated with the correct conda environment. The displayed `requirements.txt` is in project `weaver`, and so is displayed the currently installed packages (ie: all the ones in the file are installed, since `pip install -r requirements.txt` was run just before).

For some reason in that case, the plugin detects and installs "missing" packages in `fileServer` conda env... to demonstrate this, I manually pip installed `docker` package in that environment, and as presented in the figure, `docker` is suddenly detected, although this file is in the `weaver` project.

![image](https://user-images.githubusercontent.com/19194484/149382476-9fa13f51-1b67-4cdb-b43d-407d30816a31.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
- OS: Ubuntu 20.04
- PyCharm 2021.3.1 (Professional Edition)
- Build #PY-213.6461.77, built on December 28, 2021
- Runtime version: 11.0.13+7-b1751.21 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2021.4.1-213-EAP-SNAPSHOT

**Comment by meanmail** [comment]
@fmigneault fixed
