### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by ssproessig-thales** [meanmail-dev/requirements#92]
Hi all,
judging 
https://github.com/meanmail-dev/requirements/pull/90  finally fixes https://github.com/meanmail-dev/requirements/issues/87#issuecomment-1249056599  - a really important fix for daily work with this execellent plugin.

Do you guys (@meanmail @mkniewallner ) maybe need any help here, e.g. as maintainers?

**Comment by mkniewallner** [comment]
I am **NOT** a maintainer of this project, all I did is [a single PR](https://github.com/meanmail-dev/requirements/pull/67) in the past that fixes a typo, so **don't ping me**.

**Comment by meanmail** [comment]
> Is the project still maintained?

Yes
